[project]
name = "backend"
version = "0.1.0"
description = "FastAPI backend server"
authors = [
    { name = "Yi Liu" },
    { name = "Tom Gaunt" },
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "uvicorn>=0.35.0",
]

[tool.ruff]
line-length = 79
