[global]

# By default, Streamlit checks if the Python watchdog module is available
# and, if not, prints a warning asking for you to install it. The watchdog
# module is not required, it's just an optimization. Set this to True to
# suppress the warning.
disableWatchdogWarning = false

[server]

# List of folders that should not be watched for changes. This impacts both
# "Run on Save" and @st.cache.
# Relative paths will be taken as relative to the current working directory.
# Example: ['/home/user1/env', 'relative/path/to/folder']
folderWatchBlacklist = []

# Change the type of file watcher used by Streamlit, or turn it off completely.
# Allowed values:
# * "auto"     : Streamlit will attempt to use the watchdog module, and
#                falls back to polling if watchdog is not available.
# * "watchdog" : Force Streamlit to use the watchdog module.
# * "poll"     : Force Streamlit to always use polling.
# * "none"     : Streamlit will not watch files.
fileWatcherType = "auto"

# Symmetric key used to produce signed cookies. If deploying on multiple replicas,
# ensure that this is set to the same value across all replicas to ensure they all
# share the same secret.
# Default: randomly generated secret key.
cookieSecret = "mr-kg-webapp-secret"

# If false, will attempt to open a browser window on start.
headless = true

# Automatically rerun script when the file is modified on disk.
runOnSave = true

# The address where the server will listen for client and browser connections.
# Use this if you want to bind the server to a specific address. If set, the
# server will only be accessible from this address, and not from any aliases
# (like localhost).
address = "0.0.0.0"

# The port where the server will listen for client and browser connections.
port = 8501

# The base path for the URL where Streamlit should be reachable.
baseUrlPath = "/mr-kg"

# Enables support for Cross-Origin Resource Sharing (CORS) protection, for
# added security.
enableCORS = false

# Enables support for Cross-Site Request Forgery (XSRF) protection, for added
# security.
enableXsrfProtection = true

# Max size, in megabytes, for files uploaded with the file_uploader.
maxUploadSize = 200

# Max size, in megabytes, of messages that can be sent via the WebSocket
# connection.
maxMessageSize = 200

# Enables support for websocket compression.
enableWebsocketCompression = false

[browser]

# Internet address where users should point their browsers in order to connect
# to the app. Can be IP address or DNS name and path.
# This is used to:
# - Set the correct URL for CORS and XSRF protection purposes.
# - Show the URL on the terminal
# - Open the browser
# Example: http://my-domain.com:9999/my-app-path
serverAddress = "localhost"

# Whether to send usage statistics to Streamlit.
gatherUsageStats = false

# Port where users should point their browsers in order to connect to the
# app. This can be different from the port where the server listens
# (server.port) when, for example, a reverse proxy is used.
serverPort = 8501

[mapbox]

# Configure Streamlit to use a custom Mapbox
# token for elements like st.pydeck_chart and st.map.
# To get a token for yourself, create an account at
# https://mapbox.com. It's free (for moderate usage levels)!
token = ""

[deprecation]

# Set to false to disable the deprecation warning for the file uploader encoding.
showfileUploaderEncoding = false

# Set to false to disable the deprecation warning for using the global pyplot instance.
showPyplotGlobalUse = false

[theme]

# Gruvbox dark theme
# Reference: docs/misc/gruvbox-dark.toml

# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
base = "dark"

# Primary accent color for interactive elements.
# Gruvbox bright blue
primaryColor = "#83a598"

# Background color for the main content area.
# Gruvbox dark background
backgroundColor = "#282828"

# Background color used for the sidebar and most interactive widgets.
# Gruvbox slightly lighter background
secondaryBackgroundColor = "#3c3836"

# Color used for almost all text.
# Gruvbox foreground (bright white)
textColor = "#ebdbb2"

# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
font = "sans serif"
